[package]
name = "bouncycastle-core-test-framework"
version.workspace = true
edition.workspace = true

[features]
default = ["bouncycastle-rng"]
bouncycastle-rng = [
    "bouncycastle-core/bouncycastle-rng",
]

[dependencies]
bouncycastle-core = { workspace = true, default-features = false }

[dev-dependencies]
