[workspace]
members = ["cli", "crypto/*", "mem_usage_benches"]

[workspace.package]
edition = "2024"
version = "0.1.3"

[workspace.dependencies]

# *** Internal Dependencies ***
# All packages that care about the "alloc" feature enable it (and therefore std) by default, for convenience.
# Therefore, this section forces "default-features = false" to be default inherited dependency for all of these packages
# This is required so that the "alloc" feature can be disabled. Otherwise, the inherited workspace dependencies defined
# here would enable "alloc" for those packages when used as a dependency, which would propagate throughout the entire
# workspace through their dependencies, and feature unification would prevent non-"alloc" packages from being built.
bouncycastle = { path = "./" }
bouncycastle-base64 = { path = "./crypto/base64", default-features = false }
bouncycastle-core = { path = "crypto/core", default-features = false }
bouncycastle-core-test-framework = { path = "./crypto/core-test-framework", default-features = false }
# factory does not currently support building without "alloc"
# anything depending on factory will propagate "alloc" through its dependencies
bouncycastle-factory = { path = "./crypto/factory" }
bouncycastle-hex = { path = "./crypto/hex", default-features = false }
bouncycastle-hkdf = { path = "./crypto/hkdf", default-features = false }
bouncycastle-hmac = { path = "./crypto/hmac", default-features = false }
bouncycastle-mlkem = { path = "./crypto/mlkem", default-features = false }
bouncycastle-mlkem-lowmemory = { path = "./crypto/mlkem-lowmemory", default-features = false }
bouncycastle-mldsa = { path = "./crypto/mldsa", default-features = false }
bouncycastle-mldsa-lowmemory = { path = "./crypto/mldsa-lowmemory", default-features = false }
bouncycastle-rng = { path = "./crypto/rng", default-features = false }
bouncycastle-sha2 = { path = "./crypto/sha2", default-features = false }
bouncycastle-sha3 = { path = "./crypto/sha3", default-features = false }
bouncycastle-utils = { path = "./crypto/utils", default-features = false }


# *** External Dependencies ***
criterion = "0.8.2" # only for benchmarking, not used in lib or cli build

[profile.release]
lto = "thin"
strip = "debuginfo"


# libbouncycastle
[package]
name = "bouncycastle"
version.workspace = true
edition.workspace = true

# The umbrella crate re-exports the whole library for downstream users who want everything in one dependency.
# All packages (except factory) use default = ["alloc"], so building the workspace or "bouncycastle" root package
# will result in "alloc" being enabled for all packages
# "--no-default-features" not yet supported for building entire workspace or root package without "alloc"
[dependencies]
bouncycastle-base64.workspace = true
bouncycastle-core.workspace = true
bouncycastle-factory.workspace = true
bouncycastle-hex.workspace = true
bouncycastle-hkdf.workspace = true
bouncycastle-hmac.workspace = true
bouncycastle-mldsa.workspace = true
bouncycastle-mldsa-lowmemory.workspace = true
bouncycastle-mlkem.workspace = true
bouncycastle-mlkem-lowmemory.workspace = true
bouncycastle-rng.workspace = true
bouncycastle-sha2.workspace = true
bouncycastle-sha3.workspace = true
