[package]
name = "bouncycastle-rng"
version.workspace = true
edition.workspace = true

[features]
default = ["std"]
std = [
    "bouncycastle-core/std",
    "bouncycastle-core-test-framework/std"
]

[dependencies]
bouncycastle-core = { workspace = true, default-features = false }
bouncycastle-sha2.workspace = true
bouncycastle-utils.workspace = true

# external
getrandom = "0.4.0-rc.1"

[dev-dependencies]
bouncycastle-core-test-framework = { workspace = true, default-features = false }
criterion.workspace = true

[[bench]]
name = "hash_drbg_benches"
harness = false
