[package]
name = "bouncycastle-sha2"
version = "0.1.2"
edition.workspace = true

[features]
# `alloc` enables the `Vec`-returning convenience APIs (and turns on the same feature in
# bouncycastle-core). On by default; disable with `default-features = false` for `no_std` use.
default = ["alloc"]
# enable `alloc` in bouncycastle-core if enabled here
alloc = ["bouncycastle-core/alloc", "bouncycastle-rng/alloc"]

[dependencies]
bouncycastle-core = { workspace = true, default-features = false }
bouncycastle-utils.workspace = true

[dev-dependencies]
criterion.workspace = true
bouncycastle-core-test-framework.workspace = true
bouncycastle-rng = { workspace = true, default-features = false }

[[bench]]
name = "sha2_benches"
harness = false
