[package]
name = "bouncycastle-sha2"
version.workspace = true
edition.workspace = true

[features]
default = ["std"]
std = [
    "bouncycastle-core/std",
    "bouncycastle-core-test-framework/std",
    "bouncycastle-rng/std"
]

[dependencies]
bouncycastle-core = { workspace = true, default-features = false }
bouncycastle-utils.workspace = true

[dev-dependencies]
criterion.workspace = true
bouncycastle-core-test-framework = { workspace = true, default-features = false }
bouncycastle-rng = { workspace = true, default-features = false }

[[bench]]
name = "sha2_benches"
harness = false
